@startuml

!pragma teoz true

skinparam participant {
    BackgroundColor Black
    BorderColor Black
    FontColor White
}

skinparam sequence {
    ArrowColor Black
    LifeLineBorderColor Black
    LifeLineBackgroundColor Black
    LifeLineFontColor White
    ArrowFontStyle Bold
}

box "AutomatedSystem" #F8F8FF

    box "RSU" #LightSeaGreen
    participant RSUServiceNode
    participant ArrowheadCommunicaterRegister
    end box

    box "Arrowhead" #LightYellow
    participant ServiceRegistry
    end box

end box

activate RSUServiceNode
RSUServiceNode -> ArrowheadCommunicaterRegister: sends request to register a service
activate ArrowheadCommunicaterRegister

ArrowheadCommunicaterRegister -> ServiceRegistry: sends POST request to register the RSU service {Body: ServiceInformation}
activate ServiceRegistry

ServiceRegistry --> ArrowheadCommunicaterRegister: sends 201 Created with RSU Service created {Body: ServiceCreated}
deactivate ServiceRegistry

ArrowheadCommunicaterRegister -> ArrowheadCommunicaterRegister: filtersServiceID()

ArrowheadCommunicaterRegister --> RSUServiceNode: sends the service ID
deactivate ArrowheadCommunicaterRegister

RSUServiceNode -> RSUServiceNode: starts the RSU service

@enduml

